url: http://magento-ce-23.narvar.qa/index.php/rest/default/V1/order/{order_id}/invoice
httpmethod: POST
static-headers:
    Content-Type: application/json
    Authorization: Bearer fsexf38c8lnzpopdj0ztvvpzsqh6nxn9
    
post-request-json-file-path: ../magento/invoice-payload.json
post-request-json-dynamic-fields:
  order_id: identity

identity:
  start: 31
  increment: 1

#Vegeta
rate: 1 #Vegeta attack rate
duration: 5 #Vegeta attack duration

#Dump
dump-request-file-path: ../magento/magento_output/request_dump.json
dump-attack-results-file-path: ../magento/magento_output/results.bin